### ISSUE TITLE
About PKU MMD dataset

### ISSUE THREAD

**Issue by maoyunyao** [fmthoker/skeleton-contrast#3]
Nice work! I am currently following your **skeleton-contrast** and trying to run it on the PKU MMD dataset. May I have a copy of the data processing code and the training/testing configurations? Thanks in advance~

**Comment by fmthoker** [comment]
Basically, I extracted the individual actions using temporal detection annotations and then treat them as independent videos.  Then, you can follow the same procedure as given for  NTU. I will have a look and see if can find the PKU MMD processing.

**Comment by maoyunyao** [comment]
It works! Thanks a lot~

**Comment by maoyunyao** [comment]
Sorry for troubling again! I tried to download Phase #1 of the PKU-MMD dataset at [https://www.icst.pku.edu.cn/struct/Projects/PKUMMD.html](url) but the google-drive seems doesn't work for now. If possible, could you kindly share the Phase #1 data with me? Many thanks.

**Comment by dingli-dean** [comment]
Hello, could you share the processed videos of PKU-MMD?
Thanks a lot.

> Basically, I extracted the individual actions using temporal detection annotations and then treat them as independent videos. Then, you can follow the same procedure as given for NTU. I will have a look and see if can find the PKU MMD processing.

**Comment by fmthoker** [comment]
@maoyunyao  you can download pkummd datasets from https://www.icst.pku.edu.cn/struct/Projects/PKUMMD.html I just confirmed it.
@dingli93 I don't have any space to do it yet. Will see if I can find any.
