### ISSUE TITLE
how can I find the supplementary material

### ISSUE THREAD

**Issue by wmingdao** [fmthoker/skeleton-contrast#5]
Hi, Thank you for your job. In your paper, you refer to more detail of downstream tasks are discussed in the supplementary material. Please where is the supplementary material? I can't find it anywhere.

**Comment by fmthoker** [comment]
You can find that in the arxiv version.
https://arxiv.org/pdf/2108.03656.pdf

**Comment by wmingdao** [comment]
Thank you very much
