### ISSUE TITLE
Could you please upload the configs of the pre-trained model?

### ISSUE THREAD

**Issue by luyg45** [fmthoker/skeleton-contrast#9]
Hi,

This is excellent work. I used the pre-trained model you offered in my project and got good results. When I want to train a CL model using the inter-skeleton method, my reproduced model performs worse than yours. Could you please upload the configs of how you trained the pre-trained model? That will help me a lot, thanks.

**Comment by fmthoker** [comment]
@luyg45 
The configuration is already in the [scripts_pretrain.sh](https://github.com/fmthoker/skeleton-contrast/blob/main/script_pretrain.sh).
Which command/configuration did you use for pretraining?

**Comment by luyg45** [comment]
Thank you for your help. I have solved this.
